apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-add-mi-appinsights
  description: test-add-mi-appinsights
  annotations:
    github.com/project-slug: defra-adp-sandpit/test-add-mi-appinsights
    dev.azure.com/project: DEFRA-ADP
    dev.azure.com/build-definition: test-add-mi-appinsights
    sonarqube.org/project-key: test-add-mi-appinsights
    grafana/dashboard-selector: "folderTitle == 'Managed Prometheus'"
    backstage.io/kubernetes-id: test-add-mi-appinsights
  links:
    - url: https://github.com/defra-adp-sandpit/test-add-mi-appinsights
      title: GitHub Repository
      icon: github
    - url: https://dev.azure.com/defragovuk/DEFRA-ADP
      title: Azure DevOps Project
      icon: project
    - url: https://sonarcloud.io/project/overview?id=test-add-mi-appinsights
      title: SonarCloud Analysis
      icon: check
    - url: https://snyk.io/test/github/DEFRA/test-add-mi-appinsights
      title: Snyk Analysis
      icon: policy
    - url: https://portal.azure.com/defradev.onmicrosoft.com
      title: Azure Portal - Defra Dev
      icon: cloud
    - url: https://portal.azure.com/Defra.onmicrosoft.com
      title: Azure Portal - Defra
      icon: cloud
spec:
  type: backend
  lifecycle: alpha
  owner: group:default/fcp-jkr-demo
  system: system:default/adp-shared-services
